# Generated by Django 6.1.1 on 2026-09-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auths", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
    ]
